### ISSUE TITLE
Frontend Mentor was a great contribution to me

### ISSUE THREAD

**Issue by AnderMendoza** [0laolu/Todo-App#14]
I just checked the Frontend Mentor website and it's great to reinforce my knowledge, thanks. Do you know any other?

**Comment by 0laolu** [comment]
> I just checked the Frontend Mentor website and it's great to reinforce my knowledge, thanks. Do you know any other?

Any other sites you could use to reinforce your knowledge?
It really depends on you and what you want to focus on. You can have a look at sites like freeCodeCamp, there are projects there you could lay your hands on
You could check Codewell too.
Javascript30, if you'd want to improve your knowledge in JS
And lastly, Frontend mentor challenges

**Comment by AnderMendoza** [comment]
I dedicate myself more to the front end, so this type of material is very useful to me, thanks again for the information

**Comment by 0laolu** [comment]
> I dedicate myself more to the front end, so this type of material is very useful to me, thanks again for the information

Sure, you’re welcome. Goodluck going forward
