### ISSUE TITLE
[FEATURE] Implement the dark mode feature 

### ISSUE THREAD

**Issue by 0laolu** [0laolu/Todo-App#9]

**Comment by abitsalihu** [comment]
Could this be done by giving reverse colors with a class to elements in the html on the click of the dark mode button?

**Comment by 0laolu** [comment]
> Could this be done by giving reverse colors with a class to elements in the html on the click of the dark mode button?

I don't know, yet. I'm going to make research on how to get it done

**Comment by abitsalihu** [comment]
I would love to give it a try, if you would let me?

**Comment by 0laolu** [comment]
That's fine, and I'll appreciate that. But it's a project I plan to work on alone since I'm just starting out.
Although you're welcome to practice it on your own if you'd like

**Comment by abitsalihu** [comment]
Oh that's okay, hope you figure it out, have fun! :)

**Comment by 0laolu** [comment]
Thank you so much!
